### ISSUE TITLE
EPIC: Workout creator

### ISSUE THREAD

**Issue by LingVuDev** [LingVuDev/WorkoutApp#1]
#### Epic Story

As a user, I need an interface to create workouts to start workout

#### Hypotheses

We believe that adding a workout creator is the core functionality.

#### Description

This workout builder should have:
* [ ] Saved templates to have quick access to the created workouts
* [ ] Form to create exercises for the workouts
* [ ] An overview page to access all informations at once
